/* Copyright (c) 2017-2026, Hans Erik Thrane */

#include <catch2/catch_all.hpp>

#include "roq/core/json/buffer_stack.hpp"

#include "roq/kucoin_pro/json/instrument_ack.hpp"

using namespace roq;
using namespace roq::kucoin_pro;

using namespace std::literals;

using value_type = json::InstrumentAck;

// note! truncated
TEST_CASE("simple", "[json_instrument_ack]") {
  auto message = R"({)"
                 R"("code":"200000",)"
                 R"("data":{)"
                 R"("tradeType":"FUTURES",)"
                 R"("list":[{)"
                 R"("symbol":"XBTUSDTM",)"
                 R"("name":"XBTUSDTM",)"
                 R"("baseCurrency":"XBT",)"
                 R"("displayBaseCurrency":"XBT",)"
                 R"("quoteCurrency":"USDT",)"
                 R"("maxBaseOrderSize":"1000000",)"
                 R"("tickSize":"0.1",)"
                 R"("tradingStatus":"1",)"
                 R"("settlementCurrency":"USDT",)"
                 R"("contractType":"0",)"
                 R"("isInverse":false,)"
                 R"("launchTime":1585555200000,)"
                 R"("expiryTime":null,)"
                 R"("settlementTime":null,)"
                 R"("maxPrice":"1000000.0",)"
                 R"("lotSize":"1",)"
                 R"("unitSize":"0.001",)"
                 R"("makerFeeRate":"0.00020",)"
                 R"("takerFeeRate":"0.00060",)"
                 R"("settlementFeeRate":null,)"
                 R"("maxLeverage":125,)"
                 R"("indexSourceExchanges":[)"
                 R"("okex",)"
                 R"("binance",)"
                 R"("kucoin",)"
                 R"("bybit",)"
                 R"("bitmart",)"
                 R"("gateio")"
                 R"(],)"
                 R"("k":"490.0",)"
                 R"("m":"300.0",)"
                 R"("f":"1.3",)"
                 R"("mmrLimit":"0.3",)"
                 R"("mmrLevConstant":"125.0")"
                 R"(},{)"
                 R"("symbol":"ETHUSDTM",)"
                 R"("name":"ETHUSDTM",)"
                 R"("baseCurrency":"ETH",)"
                 R"("displayBaseCurrency":"ETH",)"
                 R"("quoteCurrency":"USDT",)"
                 R"("maxBaseOrderSize":"1000000",)"
                 R"("tickSize":"0.01",)"
                 R"("tradingStatus":"1",)"
                 R"("settlementCurrency":"USDT",)"
                 R"("contractType":"0",)"
                 R"("isInverse":false,)"
                 R"("launchTime":1591086000000,)"
                 R"("expiryTime":null,)"
                 R"("settlementTime":null,)"
                 R"("maxPrice":"1000000.0",)"
                 R"("lotSize":"1",)"
                 R"("unitSize":"0.01",)"
                 R"("makerFeeRate":"0.00020",)"
                 R"("takerFeeRate":"0.00060",)"
                 R"("settlementFeeRate":null,)"
                 R"("maxLeverage":100,)"
                 R"("indexSourceExchanges":[)"
                 R"("okex",)"
                 R"("binance",)"
                 R"("kucoin",)"
                 R"("gateio",)"
                 R"("bybit",)"
                 R"("bitget")"
                 R"(],)"
                 R"("k":"6610.0",)"
                 R"("m":"4110.0",)"
                 R"("f":"1.3",)"
                 R"("mmrLimit":"0.3",)"
                 R"("mmrLevConstant":"100.0")"
                 R"(},{)"
                 R"("symbol":"ZRXUSDTM",)"
                 R"("name":"ZRXUSDTM",)"
                 R"("baseCurrency":"ZRX",)"
                 R"("displayBaseCurrency":"ZRX",)"
                 R"("quoteCurrency":"USDT",)"
                 R"("maxBaseOrderSize":"100000",)"
                 R"("tickSize":"0.00010",)"
                 R"("tradingStatus":"1",)"
                 R"("settlementCurrency":"USDT",)"
                 R"("contractType":"0",)"
                 R"("isInverse":false,)"
                 R"("launchTime":1681459200000,)"
                 R"("expiryTime":null,)"
                 R"("settlementTime":null,)"
                 R"("maxPrice":"1000000.0",)"
                 R"("lotSize":"1",)"
                 R"("unitSize":"10.0",)"
                 R"("makerFeeRate":"0.00020",)"
                 R"("takerFeeRate":"0.00060",)"
                 R"("settlementFeeRate":null,)"
                 R"("maxLeverage":30,)"
                 R"("indexSourceExchanges":[)"
                 R"("bybit",)"
                 R"("okex",)"
                 R"("binance",)"
                 R"("bitmart",)"
                 R"("kucoin")"
                 R"(],)"
                 R"("k":"1359044.0",)"
                 R"("m":"852000.0",)"
                 R"("f":"1.3",)"
                 R"("mmrLimit":"0.3",)"
                 R"("mmrLevConstant":"30.0")"
                 R"(})"
                 R"(])"
                 R"(})"
                 R"(})"sv;
  auto helper = [](value_type const &obj) {
    CHECK(obj.code == 200000);
    // REQUIRE(std::size(obj.data) == 3);
  };
  core::json::BufferStack buffers{8192, 2};
  value_type obj{message, buffers};
  helper(obj);
}
