/* Copyright (c) 2017-2026, Hans Erik Thrane */

#include <catch2/catch_all.hpp>

#include "roq/core/json/buffer_stack.hpp"

#include "roq/kucoin_pro/protocol/json/currency_ack.hpp"

using namespace roq;
using namespace roq::kucoin_pro;

using namespace std::literals;

using value_type = protocol::json::CurrencyAck;

// note! truncated
TEST_CASE("simple", "[json_currency_ack]") {
  auto message = R"({)"
                 R"("code":"200000",)"
                 R"("data":{)"
                 R"("currency":"BTC",)"
                 R"("name":"BTC",)"
                 R"("fullName":"Bitcoin",)"
                 R"("precision":8,)"
                 R"("confirms":null,)"
                 R"("contractAddress":null,)"
                 R"("list":[{)"
                 R"("chainName":"BTC",)"
                 R"("minWithdrawSize":"0.00018",)"
                 R"("minDepositSize":"0.00003",)"
                 R"("withdrawFeeRate":"0",)"
                 R"("minWithdrawFee":"0.00009",)"
                 R"("isWithdrawEnabled":true,)"
                 R"("isDepositEnabled":true,)"
                 R"("confirms":3,)"
                 R"("preConfirms":1,)"
                 R"("contractAddress":"",)"
                 R"("withdrawPrecision":8,)"
                 R"("maxWithdrawSize":null,)"
                 R"("maxDepositSize":null,)"
                 R"("needTag":false,)"
                 R"("chainId":"btc")"
                 R"(},{)"
                 R"("chainName":"BEP20",)"
                 R"("minWithdrawSize":"0.000008",)"
                 R"("minDepositSize":null,)"
                 R"("withdrawFeeRate":"0",)"
                 R"("minWithdrawFee":"0.000004",)"
                 R"("isWithdrawEnabled":true,)"
                 R"("isDepositEnabled":true,)"
                 R"("confirms":60,)"
                 R"("preConfirms":15,)"
                 R"("contractAddress":"0x7130d2a12b9bcbfae4f2634d864a1ee1ce3ead9c",)"
                 R"("withdrawPrecision":8,)"
                 R"("maxWithdrawSize":null,)"
                 R"("maxDepositSize":null,)"
                 R"("needTag":false,)"
                 R"("chainId":"bsc")"
                 R"(},{)"
                 R"("chainName":"Lightning Network",)"
                 R"("minWithdrawSize":"0.00004",)"
                 R"("minDepositSize":"0.00001",)"
                 R"("withdrawFeeRate":"0",)"
                 R"("minWithdrawFee":"0.00002",)"
                 R"("isWithdrawEnabled":true,)"
                 R"("isDepositEnabled":true,)"
                 R"("confirms":1,)"
                 R"("preConfirms":1,)"
                 R"("contractAddress":"",)"
                 R"("withdrawPrecision":8,)"
                 R"("maxWithdrawSize":null,)"
                 R"("maxDepositSize":"0.03",)"
                 R"("needTag":false,)"
                 R"("chainId":"btcln")"
                 R"(},{)"
                 R"("chainName":"KCC",)"
                 R"("minWithdrawSize":"0.0008",)"
                 R"("minDepositSize":null,)"
                 R"("withdrawFeeRate":"0",)"
                 R"("minWithdrawFee":"0.00002",)"
                 R"("isWithdrawEnabled":true,)"
                 R"("isDepositEnabled":true,)"
                 R"("confirms":20,)"
                 R"("preConfirms":20,)"
                 R"("contractAddress":"0xfa93c12cd345c658bc4644d1d4e1b9615952258c",)"
                 R"("withdrawPrecision":8,)"
                 R"("maxWithdrawSize":null,)"
                 R"("maxDepositSize":null,)"
                 R"("needTag":false,)"
                 R"("chainId":"kcc")"
                 R"(},{)"
                 R"("chainName":"ARBITRUM",)"
                 R"("minWithdrawSize":"0.0005",)"
                 R"("minDepositSize":null,)"
                 R"("withdrawFeeRate":"0",)"
                 R"("minWithdrawFee":"0.0001",)"
                 R"("isWithdrawEnabled":false,)"
                 R"("isDepositEnabled":false,)"
                 R"("confirms":1900,)"
                 R"("preConfirms":120,)"
                 R"("contractAddress":"0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f",)"
                 R"("withdrawPrecision":8,)"
                 R"("maxWithdrawSize":null,)"
                 R"("maxDepositSize":null,)"
                 R"("needTag":false,)"
                 R"("chainId":"arbitrum")"
                 R"(},{)"
                 R"("chainName":"BTC-Segwit",)"
                 R"("minWithdrawSize":"0.0008",)"
                 R"("minDepositSize":"0.0001",)"
                 R"("withdrawFeeRate":"0",)"
                 R"("minWithdrawFee":"0.0005",)"
                 R"("isWithdrawEnabled":false,)"
                 R"("isDepositEnabled":true,)"
                 R"("confirms":2,)"
                 R"("preConfirms":2,)"
                 R"("contractAddress":"",)"
                 R"("withdrawPrecision":8,)"
                 R"("maxWithdrawSize":null,)"
                 R"("maxDepositSize":null,)"
                 R"("needTag":false,)"
                 R"("chainId":"bech32")"
                 R"(})"
                 R"(])"
                 R"(})"
                 R"(})"sv;
  auto helper = [](value_type const &obj) {
    CHECK(obj.code == 200000);
    // REQUIRE(std::size(obj.data) == 3);
  };
  core::json::BufferStack buffers{8192, 2};
  value_type obj{message, buffers};
  helper(obj);
}
